language: shell

branches:
    only:
    - master

dist: bionic

python:
  - "3.8-dev"  # 3.8 development branch

before_install:
  - sudo apt-get install python3-pip python3-setuptools python3-wheel -y
  - python3 -m pip install wheel selenium

script:
  - sudo python3 actions.py
 
