# This is a basic workflow to help you get started with Actions
name: rt-thread club automatic check-in

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # runs at 00:00 UTC every day
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Sign In
      env:
        CLUB_USERNAME: ${{ secrets.USERNAME }}
        CLUB_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python actions.py
        echo "::set-env name=CLUB_DAY_NUMERS::$(cat sign_in_days.txt)"
    - name: 'Get Date'
      run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
    - name: Send email
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 签到小助手提醒您 (${{env.REPORT_DATE}})
        body: ${{env.CLUB_DAY_NUMERS}}
        to: ${{ secrets.TEST_EMAIL }}
        from: GitHub Actions
        content_type: text/html
        attachments: /home/runner/paihang.png
