name: rt-thread-club

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs on the 0, 4, 8, 12, 16 and 20th hour every day
  schedule:
    - cron:  '0 */6 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Sign In
      run: |
        python actions.py
        echo $(cat sign_in_days.txt) >> PRIVATE_DAY_INFO
        echo "command"
        echo $(cat sign_in_days.txt)
        echo "value"
        echo ${{ env.PRIVATE_DAY_INFO }}
      env:
        CLUB_USERNAME: ${{ secrets.USERNAME }}
        CLUB_PASSWORD: ${{ secrets.PASSWORD }}
        # PRIVATE_DAY_INFO: $(cat sign_in_days.txt)
    # - name: 'Get Date'
    #   run: |
    #     echo $(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T') > date_info
    #     echo "command"
    #     echo $(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')
    #     echo "value"
    #     echo ${{ env.PRIVATE_REPORT_DATE}}
    #   env:
    #     PRIVATE_REPORT_DATE: ${date_info}
    # - name: Send email
    #   uses: dawidd6/action-send-mail@master
    #   with:
    #     server_address: smtp.qq.com
    #     server_port: 465
    #     username: ${{ secrets.MAIL_USERNAME }}
    #     password: ${{ secrets.EMAIL_PASSWORD }}
    #     subject: 签到成功 ${{ env.PRIVATE_REPORT_DATE }}      # only support text
    #     body: ${{ env.PRIVATE_DAY_INFO  }} -xiangxistu        # only support text
    #     to: ${{ secrets.TEST_EMAIL }}
    #     from: GitHub Actions
    #     content_type: text/html
    #     attachments: /home/runner/paihang.png
