name: rt-thread-club

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs on the 0, 4, 8, 12, 16 and 20th hour every day
  schedule:
    - cron:  '0 */4 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Sign In
      run: |
        python actions.py
        # echo "::set-env name=CLUB_DAY_INFO::$(cat sign_in_days.txt)"
      env:
        CLUB_USERNAME: ${{ secrets.USERNAME }}
        CLUB_PASSWORD: ${{ secrets.PASSWORD }}
    - name: 'Get Date'
      run: |
        # echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
        echo "TZ=':Asia/Shanghai' date '+%Y-%m-%d %T"
    - name: Send email
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 签到小助手提醒您 (TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')
        body: cat sign_in_days.txt
        to: ${{ secrets.TEST_EMAIL }}
        from: GitHub Actions
        content_type: text/html
        attachments: /home/runner/paihang.png
